const STORAGE_KEY='ymsh-classroom-map-v1';
const buildings=[
 {id:'mingde',name:'明德樓',sub:'專科教室大樓',floors:['B1','1F','2F','3F','4F','5F']},{id:'junior',name:'圖中教學大樓',sub:'國中部',floors:['1F','2F','3F','4F']},{id:'senior1',name:'立志樓',sub:'高一教學大樓',floors:['1F','2F','3F','4F']},{id:'science',name:'科學樓',sub:'自然科教室',floors:['B1','1F','2F','3F','4F']},{id:'senior2',name:'向陽樓',sub:'高二教學大樓',floors:['1F','2F','3F','4F']},{id:'zhixing',name:'知行館',sub:'教師與輔導空間',floors:['1F','2F']},{id:'senior3',name:'勤學樓',sub:'高三教學大樓',floors:['1F','2F','3F','4F']},{id:'admin',name:'行政樓',sub:'行政辦公空間',floors:['1F','2F']},{id:'yicai',name:'藝采樓',sub:'藝術與圖書空間',floors:['1F','2F','3F']},{id:'gym',name:'漾泉館',sub:'溫水游泳池',floors:['1F']},{id:'garden',name:'中庭花園',sub:'戶外公共空間',floors:['1F']}];
const statusText={normal:'一般使用',planned:'規劃中',working:'施工中',done:'已完成'};
const baseRooms={
 junior:{'1F':['員生合作社','教東休息區','學習中心','特教組','穿堂','倉庫'],'2F':['906班','905班','904班','903班','902班','901班'],'3F':['806班','805班','804班','803班','802班','801班'],'4F':['706班','705班','704班','703班','702班','701班']},
 senior1:{'1F':['106班','語言教室','視聽教室'],'2F':['101班','102班','103班','104班'],'3F':['105班','107班','108班','109班'],'4F':['110班','111班','112班','113班']},
 senior2:{'1F':['校安中心','學務處','健康中心','306班'],'2F':['205班','212班','社團教室','交安教室','健護教室'],'3F':['207班','208班','209班','210班','211班'],'4F':['201班','202班','203班','204班','206班']},
 senior3:{'1F':['海龍班114','會議室','海龍班214','海龍班314'],'2F':['305班','304班','213班','家政1','社團教室'],'3F':['301班','302班','303班','307班','313班'],'4F':['308班','309班','310班','311班','312班']},
 mingde:{'B1':['逃生避難空間'],'1F':['國中教師辦公室','創新學習教室'],'2F':['圖書館'],'3F':['電腦教室1','管理室','電腦教室2'],'4F':['物理實驗室2','物理準備室','物理實驗室3'],'5F':['化學實驗室2','化學準備室','化學實驗室3']},
 science:{'B1':['庫房'],'1F':['地科教室','生物1'],'2F':['社科教室','設備組'],'3F':['化學1','藥品室','生物2'],'4F':['物理1','生物3']},
 zhixing:{'1F':['生涯教室','輔導室'],'2F':['教辦3','會議室','團輔室']},
 admin:{'1F':['人事室','文書室','教務處'],'2F':['會計室','家長會','簡報室','校長室']},
 yicai:{'1F':['烹飪教室','庫房','生科2（國中）'],'2F':['生科1（高中）','藝術庫房','機器教室'],'3F':['家政2','童軍教室','美術2','美術1']},
 gym:{'1F':['漾泉館（溫水游泳池）']},garden:{'1F':['中庭花園']}
};
function makeRooms(){let n=0;return buildings.flatMap(b=>Object.entries(baseRooms[b.id]||{}).flatMap(([floor,names])=>names.map(name=>{const isClass=/^\d{3}班$/.test(name);const grade=isClass?name[0]:'';const groups=grade==='2'?{g1:14,g2:14,g3:8}:null;return{id:`r${++n}`,building:b.id,floor,name,className:isClass?name:'',students:isClass?(grade==='2'?36:35):0,desks:isClass?(grade==='2'?38:36):0,status:'normal',note:'',groups,columns:6}})))}
const initial=()=>({activeYear:'115',years:{'115':{updated:new Date().toISOString(),rooms:makeRooms()}}});
let state=load(),selectedBuilding='senior2',selectedFloor='4F',filterStatus='all',query='',seatRoomId=null;
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||initial()}catch{return initial()}}
function save(msg='已儲存'){state.years[state.activeYear].updated=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render();toast(msg)}
const rooms=()=>state.years[state.activeYear].rooms;
const building=id=>buildings.find(b=>b.id===id);
function escapeHTML(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function roomMatch(r){const hay=[r.name,r.className,r.note,building(r.building)?.name,r.floor].join(' ').toLowerCase();return (!query||hay.includes(query))&&(filterStatus==='all'||r.status===filterStatus)}
function render(){renderYears();renderSummary();renderMap();renderPanel();renderTable();renderSeatSelector()}
function renderYears(){yearSelect.innerHTML=Object.keys(state.years).sort((a,b)=>b.localeCompare(a,undefined,{numeric:true})).map(y=>`<option ${y===state.activeYear?'selected':''}>${escapeHTML(y)}</option>`).join('')}
function renderSummary(){const rs=rooms(),classes=rs.filter(r=>r.className),students=classes.reduce((s,r)=>s+(+r.students||0),0),works=rs.filter(r=>['planned','working'].includes(r.status)).length;summaryRow.innerHTML=[[buildings.length,'🏫','校舍區塊'],[classes.length,'▦','班級教室'],[students,'人','學生配置'],[works,'⚒','進行／規劃工程']].map(x=>`<div class="summary"><i>${x[1]}</i><div><strong>${x[0]}</strong><span>${x[2]}</span></div></div>`).join('');['all','normal','planned','working','done'].forEach(s=>document.getElementById('count'+s[0].toUpperCase()+s.slice(1)).textContent=s==='all'?rs.length:rs.filter(r=>r.status===s).length)}
function buildingStatus(id){const ss=rooms().filter(r=>r.building===id).map(r=>r.status);return ss.includes('working')?'working':ss.includes('planned')?'planned':ss.includes('done')?'done':'normal'}
function floorOrder(b){return [...b.floors].sort((a,b)=>{if(a==='B1')return 1;if(b==='B1')return -1;return parseInt(b)-parseInt(a)})}
function floorRoomCell(r){const dim=!roomMatch(r);return`<button class="plan-room ${r.status} ${dim?'dimmed':''}" data-room="${r.id}" title="${escapeHTML(r.note||statusText[r.status])}"><strong>${escapeHTML(r.name)}</strong>${r.students?`<small>${r.students}人</small>`:''}<i class="status-pin ${r.status}"></i></button>`}
function renderMap(){const shown=buildings.filter(b=>b.id!=='garden');campusMap.innerHTML=shown.map(b=>{const br=rooms().filter(r=>r.building===b.id),visible=br.some(roomMatch);return`<section class="floor-building fb-${b.id} ${!visible?'filtered':''}" data-building="${b.id}"><header><div><strong>${b.name}</strong><span>${b.sub}</span></div><small>${br.length} 個空間</small></header><div class="floor-stack">${floorOrder(b).map(f=>{const fr=br.filter(r=>r.floor===f);return`<div class="floor-row"><b>${f}</b><div class="floor-rooms">${fr.length?fr.map(floorRoomCell).join(''):'<span class="empty-floor">未配置</span>'}</div></div>`}).join('')}</div></section>`}).join('');campusMap.querySelectorAll('[data-room]').forEach(el=>el.onclick=()=>openRoom(el.dataset.room))}
function renderPanel(){buildingPanel.innerHTML='<h2>閱讀方式</h2><p>每棟校舍以平面圖的方式呈現：</p><ol><li>最高樓層在最上方</li><li>每列房間依原圖由左至右排列</li><li>點選房間即可編輯人數、桌椅及工程狀態</li></ol><div class="guide-sample"><b>4F</b><span>201班</span><span>202班</span><span>203班</span></div>'}
function roomCard(r){return`<article class="room-card ${r.status}" data-room="${r.id}"><header><strong>${escapeHTML(r.name)}</strong><em>${statusText[r.status]}</em></header>${r.className&&r.className!==r.name?`<p>${escapeHTML(r.className)}</p>`:''}<div class="room-meta">${r.students?`<span>👥 ${r.students} 人</span>`:''}${r.desks?`<span>▦ ${r.desks} 桌椅</span>`:''}${r.note?`<span>✎ ${escapeHTML(r.note.slice(0,18))}</span>`:''}</div></article>`}
function renderTable(){const list=rooms().filter(roomMatch).sort((a,b)=>(building(a.building).name+a.floor+a.name).localeCompare(building(b.building).name+b.floor+b.name,'zh-Hant',{numeric:true}));roomListCaption.textContent=`${state.activeYear} 學年度，共 ${list.length} 筆空間資料`;roomsTable.innerHTML=list.map(r=>`<tr data-room="${r.id}"><td>${building(r.building).name}／${r.floor}</td><td><strong>${escapeHTML(r.name)}</strong></td><td>${escapeHTML(r.className||'—')}</td><td>${r.students||'—'}</td><td><span class="status-label"><i class="dot ${r.status}"></i>${statusText[r.status]}</span></td><td>${escapeHTML(r.note||'—')}</td></tr>`).join('');roomsTable.querySelectorAll('tr').forEach(x=>x.onclick=()=>openRoom(x.dataset.room))}
function openRoom(id,bid='senior1',floor='1F'){if(!editToggle.checked&&id)return;const r=id?rooms().find(x=>x.id===id):{id:'',building:bid,floor,name:'',className:'',students:0,desks:0,status:'normal',note:''};dialogTitle.textContent=id?'編輯空間':'新增空間';roomId.value=r.id;roomBuilding.innerHTML=buildings.map(b=>`<option value="${b.id}" ${b.id===r.building?'selected':''}>${b.name}</option>`).join('');roomFloor.value=r.floor;roomName.value=r.name;roomClass.value=r.className;roomStudents.value=r.students||'';roomDesks.value=r.desks||'';roomStatus.value=r.status;roomNote.value=r.note;deleteRoomBtn.hidden=!id;roomDialog.showModal()}
function renderSeatSelector(){const classRooms=rooms().filter(r=>r.className).sort((a,b)=>a.className.localeCompare(b.className,undefined,{numeric:true}));if(!seatRoomId||!classRooms.some(r=>r.id===seatRoomId))seatRoomId=classRooms[0]?.id;seatRoomSelect.innerHTML=classRooms.map(r=>`<option value="${r.id}" ${r.id===seatRoomId?'selected':''}>${r.className}｜${building(r.building).name} ${r.floor}</option>`).join('');renderSeats()}
function renderSeats(){const r=rooms().find(x=>x.id===seatRoomId);if(!r){seatGrid.innerHTML='';return}seatColumns.value=r.columns||6;seatLocation.textContent=`${building(r.building).name} · ${r.floor}`;seatTitle.textContent=r.className||r.name;seatTotal.textContent=`${r.students||0} 位學生／${r.desks||0} 張桌椅`;if(r.className?.startsWith('2')){const g=r.groups||{g1:0,g2:0,g3:0};seatInputs.innerHTML=['g1','g2','g3'].map((k,i)=>`<label>第 ${i+1} 類人數<input class="group-input" data-group="${k}" type="number" min="0" max="60" value="${g[k]||0}" /></label>`).join('')}else seatInputs.innerHTML='<p class="seat-hint">非高二班級使用一般座位配置。</p>';const count=Math.max(+r.desks||0,+r.students||0);seatGrid.style.gridTemplateColumns=`repeat(${r.columns||6},62px)`;let groups=[];if(r.groups)Object.entries(r.groups).forEach(([k,n])=>groups.push(...Array(+n||0).fill(k)));seatGrid.innerHTML=Array.from({length:count},(_,i)=>`<div class="desk ${groups[i]||'other'}">${i+1}</div>`).join('')}
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>toastEl.classList.remove('show'),1800)}
const toastEl=document.getElementById('toast');
document.querySelectorAll('.segmented button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.segmented button').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(btn.dataset.view+'View').classList.add('active');if(btn.dataset.view==='seats')renderSeatSelector()});
document.querySelectorAll('.legend').forEach(btn=>btn.onclick=()=>{filterStatus=btn.dataset.status;document.querySelectorAll('.legend').forEach(x=>x.classList.toggle('active',x===btn));renderMap();renderPanel();renderTable()});
searchInput.oninput=e=>{query=e.target.value.trim().toLowerCase();renderMap();renderPanel();renderTable()};yearSelect.onchange=e=>{state.activeYear=e.target.value;render();toast(`已切換至 ${state.activeYear} 學年度`)};editToggle.onchange=()=>renderPanel();printBtn.onclick=()=>window.print();moreBtn.onclick=()=>moreMenu.hidden=!moreMenu.hidden;document.addEventListener('click',e=>{if(!e.target.closest('.top-actions'))moreMenu.hidden=true});
newYearBtn.onclick=()=>{newYearName.value=String((parseInt(state.activeYear)||115)+1);yearDialog.showModal()};document.querySelectorAll('[data-close-year]').forEach(x=>x.onclick=()=>yearDialog.close());yearForm.onsubmit=e=>{e.preventDefault();const y=newYearName.value.trim();if(state.years[y])return toast('這個學年度已存在');state.years[y]=copyYear.checked?JSON.parse(JSON.stringify(state.years[state.activeYear])):{updated:new Date().toISOString(),rooms:[]};state.activeYear=y;yearDialog.close();save(`已建立 ${y} 學年度`)};
roomForm.onsubmit=e=>{e.preventDefault();const id=roomId.value;const old=rooms().find(x=>x.id===id);const next={...(old||{}),id:id||`r-${Date.now()}`,building:roomBuilding.value,floor:roomFloor.value,name:roomName.value.trim(),className:roomClass.value.trim(),students:+roomStudents.value||0,desks:+roomDesks.value||0,status:roomStatus.value,note:roomNote.value.trim(),columns:old?.columns||6,groups:old?.groups||null};if(id)Object.assign(old,next);else rooms().push(next);selectedBuilding=next.building;selectedFloor=next.floor;roomDialog.close();save(id?'空間資料已更新':'已新增空間')};closeDialog.onclick=cancelDialog.onclick=()=>roomDialog.close();deleteRoomBtn.onclick=()=>{if(confirm('確定要刪除此空間嗎？')){state.years[state.activeYear].rooms=rooms().filter(r=>r.id!==roomId.value);roomDialog.close();save('空間已刪除')}};addRoomBtn.onclick=()=>openRoom();
seatRoomSelect.onchange=e=>{seatRoomId=e.target.value;renderSeats()};seatColumns.oninput=()=>{const r=rooms().find(x=>x.id===seatRoomId);r.columns=Math.max(2,Math.min(10,+seatColumns.value||6));renderSeats()};saveSeatBtn.onclick=()=>{const r=rooms().find(x=>x.id===seatRoomId);r.columns=+seatColumns.value||6;if(r.className?.startsWith('2')){r.groups={};document.querySelectorAll('.group-input').forEach(i=>r.groups[i.dataset.group]=+i.value||0);r.students=Object.values(r.groups).reduce((a,b)=>a+b,0);r.desks=Math.max(r.desks,r.students)}save('座位配置已儲存')};
exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`陽明高中教室配置-${state.activeYear}.json`;a.click();URL.revokeObjectURL(a.href);toast('備份檔已匯出')};importInput.onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!data.years||!data.activeYear)throw Error();state=data;save('備份資料已匯入')}catch{toast('檔案格式不正確')}e.target.value=''};resetBtn.onclick=()=>{if(confirm('確定還原示範資料？目前修改將被取代。')){state=initial();save('已還原示範資料')}};
if(document.modelContext?.registerTool){const register=(tool)=>Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});register({name:'search_campus_spaces',title:'搜尋校園空間',description:'搜尋目前學年度的班級、教室、工程與備註。',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:({query:q})=>rooms().filter(r=>[r.name,r.className,r.note,building(r.building)?.name].join(' ').includes(q)).map(r=>({name:r.name,building:building(r.building).name,floor:r.floor,status:statusText[r.status]}))});register({name:'update_room_status',title:'更新空間工程狀態',description:'依空間名稱更新目前學年度的工程狀態與備註。',inputSchema:{type:'object',properties:{roomName:{type:'string'},status:{type:'string',enum:['normal','planned','working','done']},note:{type:'string'}},required:['roomName','status'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({roomName,status,note})=>{const r=rooms().find(x=>x.name===roomName);if(!r)throw Error('找不到空間');r.status=status;if(note!==undefined)r.note=note;save('工程狀態已更新');return{name:r.name,status:statusText[r.status],saved:true}}})}
render();
